### ISSUE TITLE
Problems when I tried Slides 00-Lab-Software-Requirements Page21

### ISSUE THREAD

**Issue by Adora2401** [nyu-devops/lab-starter#1]
Hi all,
When I tried Slides 00-Lab-Software-Requirements Page21 about SonarLint JRE, I met an error as the picture below. Do anyone know how to solve it? All the steps before this slide works on my pc. It's Mac M1 and the java version is 16.0.2
<img width="457" alt="截屏2022-02-02 下午3 12 08" src="https://user-images.githubusercontent.com/49673054/152229741-46bfc2ba-5a40-4ad3-8e99-a7cfb20aa1bb.png">
.

**Comment by rofrano** [comment]
I removed SonarLint from the VSCode extension list because it doesn't work with Apple M1 Silicon due to some Java incompatibilities. This is laughable because Java was supposed to be the "write once run anywhere" software but turned out to be the "write once _debug_ anywhere" software. It's a shame because SonarLint is a nice tool but it's requirement for Java is undesirable at best.
